name: Build and Deploy to Backend
on:
  push:
    branches: [ main ]

jobs:
  build-and-copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: aquanautpp/curio-backend
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: backend
      - name: Copy dist to backend static folder
        run: |
          rm -rf backend/src/static/*
          cp -r dist/* backend/src/static/
      - name: Commit and push to backend
        run: |
          cd backend
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/static
          git commit -m "Deploy static files from frontend [skip ci]" || echo "No changes to commit"
          git push
